### PR TITLE
fix: amounts with higher precision

### LINKED ISSUE #229: Specifying an amount that's too tiny
In send transaction dialog box, if you specify the amount that's too tiny, I.E. 0.00000000001 ARK, it still allows the process to continue and then only gives an error at the very end when trying to execute the send.  The "amount-to-send" text field should be smart enough to know when user entered amount too small, and moves focus off the text field, to then do a popup msg that says "amount is too small. send [smallest amount] instead?" Yes/No

Also, user might try to send amount as 12.000000000001, using too many decimals of precision. So the text field should be smart enough to address this on the spot instead of at the very end

### PR DESCRIPTION
**Pull request by kalgoop**
transaction_send page allowed users to enter amounts with precision of more than 8 decimal digits. These transactions were failing with status 400 after pressing the send button.
This PR fixes this bug.

## Proposed changes

Resolves #229 .

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

File: src/components/amount/amount.ts [hunk 1]
```diff
@@ -50,6 +50,7 @@ export class AmountComponent implements OnInit {
 
   public onInputToken() {
     const precision = this.marketCurrency.code === 'btc' ? 8 : 2;
+    this.amount = +(1.0 * this.amount).toFixed(8);
```
Comment (luciorubeens) [inline src/components/amount/amount.ts]: We should use the `BigNumber` package and the `ARKTOSHI_DP` constant. Take a look: https://github.com/ArkEcosystem/mobile-wallet/blob/62163ecd1e585eb7689ce7f34667cd2bd44a02d9/src/utils/ark-utility.ts#L13

**Comment by kalgoop** [comment]
@luciorubeens Updated with Bignum
